"""
Seed the nationalities SQLite table with a comprehensive list of world nationalities.
Run directly:  python -m app.db.seed_nationalities
"""

from .database import get_connection, create_tables, is_nationalities_seeded

# (nationality, country, country_code)
NATIONALITIES = [
    ("Afghan", "Afghanistan", "AF"),
    ("Albanian", "Albania", "AL"),
    ("Algerian", "Algeria", "DZ"),
    ("American", "United States", "US"),
    ("Andorran", "Andorra", "AD"),
    ("Angolan", "Angola", "AO"),
    ("Antiguan", "Antigua and Barbuda", "AG"),
    ("Argentine", "Argentina", "AR"),
    ("Armenian", "Armenia", "AM"),
    ("Australian", "Australia", "AU"),
    ("Austrian", "Austria", "AT"),
    ("Azerbaijani", "Azerbaijan", "AZ"),
    ("Bahamian", "Bahamas", "BS"),
    ("Bahraini", "Bahrain", "BH"),
    ("Bangladeshi", "Bangladesh", "BD"),
    ("Barbadian", "Barbados", "BB"),
    ("Belarusian", "Belarus", "BY"),
    ("Belgian", "Belgium", "BE"),
    ("Belizean", "Belize", "BZ"),
    ("Beninese", "Benin", "BJ"),
    ("Bhutanese", "Bhutan", "BT"),
    ("Bolivian", "Bolivia", "BO"),
    ("Bosnian", "Bosnia and Herzegovina", "BA"),
    ("Botswanan", "Botswana", "BW"),
    ("Brazilian", "Brazil", "BR"),
    ("Bruneian", "Brunei", "BN"),
    ("Bulgarian", "Bulgaria", "BG"),
    ("Burkinabe", "Burkina Faso", "BF"),
    ("Burundian", "Burundi", "BI"),
    ("Cabo Verdean", "Cabo Verde", "CV"),
    ("Cambodian", "Cambodia", "KH"),
    ("Cameroonian", "Cameroon", "CM"),
    ("Canadian", "Canada", "CA"),
    ("Central African", "Central African Republic", "CF"),
    ("Chadian", "Chad", "TD"),
    ("Chilean", "Chile", "CL"),
    ("Chinese", "China", "CN"),
    ("Colombian", "Colombia", "CO"),
    ("Comorian", "Comoros", "KM"),
    ("Congolese", "Democratic Republic of the Congo", "CD"),
    ("Costa Rican", "Costa Rica", "CR"),
    ("Croatian", "Croatia", "HR"),
    ("Cuban", "Cuba", "CU"),
    ("Cypriot", "Cyprus", "CY"),
    ("Czech", "Czech Republic", "CZ"),
    ("Danish", "Denmark", "DK"),
    ("Djiboutian", "Djibouti", "DJ"),
    ("Dominican", "Dominican Republic", "DO"),
    ("Dominicaner", "Dominica", "DM"),
    ("Dutch", "Netherlands", "NL"),
    ("East Timorese", "East Timor", "TL"),
    ("Ecuadorian", "Ecuador", "EC"),
    ("Egyptian", "Egypt", "EG"),
    ("Emirati", "United Arab Emirates", "AE"),
    ("Equatorial Guinean", "Equatorial Guinea", "GQ"),
    ("Eritrean", "Eritrea", "ER"),
    ("Estonian", "Estonia", "EE"),
    ("Eswatini", "Eswatini", "SZ"),
    ("Ethiopian", "Ethiopia", "ET"),
    ("Fijian", "Fiji", "FJ"),
    ("Filipino", "Philippines", "PH"),
    ("Finnish", "Finland", "FI"),
    ("French", "France", "FR"),
    ("Gabonese", "Gabon", "GA"),
    ("Gambian", "Gambia", "GM"),
    ("Georgian", "Georgia", "GE"),
    ("German", "Germany", "DE"),
    ("Ghanaian", "Ghana", "GH"),
    ("Greek", "Greece", "GR"),
    ("Grenadian", "Grenada", "GD"),
    ("Guatemalan", "Guatemala", "GT"),
    ("Guinean", "Guinea", "GN"),
    ("Guinea-Bissauan", "Guinea-Bissau", "GW"),
    ("Guyanese", "Guyana", "GY"),
    ("Haitian", "Haiti", "HT"),
    ("Honduran", "Honduras", "HN"),
    ("Hungarian", "Hungary", "HU"),
    ("Icelandic", "Iceland", "IS"),
    ("Indian", "India", "IN"),
    ("Indonesian", "Indonesia", "ID"),
    ("Iranian", "Iran", "IR"),
    ("Iraqi", "Iraq", "IQ"),
    ("Irish", "Ireland", "IE"),
    ("Israeli", "Israel", "IL"),
    ("Italian", "Italy", "IT"),
    ("Ivorian", "Ivory Coast", "CI"),
    ("Jamaican", "Jamaica", "JM"),
    ("Japanese", "Japan", "JP"),
    ("Jordanian", "Jordan", "JO"),
    ("Kazakh", "Kazakhstan", "KZ"),
    ("Kenyan", "Kenya", "KE"),
    ("Kiribati", "Kiribati", "KI"),
    ("Kosovar", "Kosovo", "XK"),
    ("Kuwaiti", "Kuwait", "KW"),
    ("Kyrgyz", "Kyrgyzstan", "KG"),
    ("Lao", "Laos", "LA"),
    ("Latvian", "Latvia", "LV"),
    ("Lebanese", "Lebanon", "LB"),
    ("Lesotho", "Lesotho", "LS"),
    ("Liberian", "Liberia", "LR"),
    ("Libyan", "Libya", "LY"),
    ("Liechtensteiner", "Liechtenstein", "LI"),
    ("Lithuanian", "Lithuania", "LT"),
    ("Luxembourgish", "Luxembourg", "LU"),
    ("Malagasy", "Madagascar", "MG"),
    ("Malawian", "Malawi", "MW"),
    ("Malaysian", "Malaysia", "MY"),
    ("Maldivian", "Maldives", "MV"),
    ("Malian", "Mali", "ML"),
    ("Maltese", "Malta", "MT"),
    ("Marshallese", "Marshall Islands", "MH"),
    ("Mauritanian", "Mauritania", "MR"),
    ("Mauritian", "Mauritius", "MU"),
    ("Mexican", "Mexico", "MX"),
    ("Micronesian", "Micronesia", "FM"),
    ("Moldovan", "Moldova", "MD"),
    ("Monegasque", "Monaco", "MC"),
    ("Mongolian", "Mongolia", "MN"),
    ("Montenegrin", "Montenegro", "ME"),
    ("Moroccan", "Morocco", "MA"),
    ("Mozambican", "Mozambique", "MZ"),
    ("Myanmar", "Myanmar", "MM"),
    ("Namibian", "Namibia", "NA"),
    ("Nauruan", "Nauru", "NR"),
    ("Nepalese", "Nepal", "NP"),
    ("New Zealander", "New Zealand", "NZ"),
    ("Nicaraguan", "Nicaragua", "NI"),
    ("Nigerien", "Niger", "NE"),
    ("Nigerian", "Nigeria", "NG"),
    ("North Korean", "North Korea", "KP"),
    ("North Macedonian", "North Macedonia", "MK"),
    ("Norwegian", "Norway", "NO"),
    ("Omani", "Oman", "OM"),
    ("Pakistani", "Pakistan", "PK"),
    ("Palauan", "Palau", "PW"),
    ("Palestinian", "Palestine", "PS"),
    ("Panamanian", "Panama", "PA"),
    ("Papua New Guinean", "Papua New Guinea", "PG"),
    ("Paraguayan", "Paraguay", "PY"),
    ("Peruvian", "Peru", "PE"),
    ("Polish", "Poland", "PL"),
    ("Portuguese", "Portugal", "PT"),
    ("Qatari", "Qatar", "QA"),
    ("Romanian", "Romania", "RO"),
    ("Russian", "Russia", "RU"),
    ("Rwandan", "Rwanda", "RW"),
    ("Saint Kitts and Nevis", "Saint Kitts and Nevis", "KN"),
    ("Saint Lucian", "Saint Lucia", "LC"),
    ("Saint Vincentian", "Saint Vincent and the Grenadines", "VC"),
    ("Salvadoran", "El Salvador", "SV"),
    ("Samoan", "Samoa", "WS"),
    ("San Marinese", "San Marino", "SM"),
    ("Sao Tomean", "Sao Tome and Principe", "ST"),
    ("Saudi", "Saudi Arabia", "SA"),
    ("Senegalese", "Senegal", "SN"),
    ("Serbian", "Serbia", "RS"),
    ("Seychellois", "Seychelles", "SC"),
    ("Sierra Leonean", "Sierra Leone", "SL"),
    ("Singaporean", "Singapore", "SG"),
    ("Slovak", "Slovakia", "SK"),
    ("Slovenian", "Slovenia", "SI"),
    ("Solomon Islander", "Solomon Islands", "SB"),
    ("Somali", "Somalia", "SO"),
    ("South African", "South Africa", "ZA"),
    ("South Korean", "South Korea", "KR"),
    ("South Sudanese", "South Sudan", "SS"),
    ("Spanish", "Spain", "ES"),
    ("Sri Lankan", "Sri Lanka", "LK"),
    ("Sudanese", "Sudan", "SD"),
    ("Surinamese", "Suriname", "SR"),
    ("Swedish", "Sweden", "SE"),
    ("Swiss", "Switzerland", "CH"),
    ("Syrian", "Syria", "SY"),
    ("Taiwanese", "Taiwan", "TW"),
    ("Tajik", "Tajikistan", "TJ"),
    ("Tanzanian", "Tanzania", "TZ"),
    ("Thai", "Thailand", "TH"),
    ("Togolese", "Togo", "TG"),
    ("Tongan", "Tonga", "TO"),
    ("Trinidadian", "Trinidad and Tobago", "TT"),
    ("Tunisian", "Tunisia", "TN"),
    ("Turkish", "Turkey", "TR"),
    ("Turkmen", "Turkmenistan", "TM"),
    ("Tuvaluan", "Tuvalu", "TV"),
    ("Ugandan", "Uganda", "UG"),
    ("Ukrainian", "Ukraine", "UA"),
    ("Uruguayan", "Uruguay", "UY"),
    ("Uzbek", "Uzbekistan", "UZ"),
    ("Vanuatuan", "Vanuatu", "VU"),
    ("Vatican", "Vatican City", "VA"),
    ("Venezuelan", "Venezuela", "VE"),
    ("Vietnamese", "Vietnam", "VN"),
    ("Yemeni", "Yemen", "YE"),
    ("Zambian", "Zambia", "ZM"),
    ("Zimbabwean", "Zimbabwe", "ZW"),
    # Common alternate demonyms
    ("British", "United Kingdom", "GB"),
    ("Scottish", "United Kingdom", "GB"),
    ("Welsh", "United Kingdom", "GB"),
    ("English", "United Kingdom", "GB"),
    ("Hong Konger", "Hong Kong", "HK"),
    ("Macanese", "Macau", "MO"),
    ("Puerto Rican", "Puerto Rico", "PR"),
]


def seed():
    """Seed the nationalities table if empty."""
    create_tables()
    if is_nationalities_seeded():
        return

    with get_connection() as conn:
        conn.executemany(
            "INSERT OR IGNORE INTO nationalities (nationality, country, country_code) VALUES (?, ?, ?)",
            NATIONALITIES,
        )
        conn.commit()


if __name__ == "__main__":
    seed()
    print(f"Seeded {len(NATIONALITIES)} nationalities.")
