"""
Seed the airports SQLite database with a comprehensive list of worldwide airports.
Run directly:  python -m app.db.seed_airports
"""

from .database import get_connection, create_tables

# (iata_code, icao_code, name, city, country, country_code, lat, lon)
AIRPORTS = [
    # ── United States ──────────────────────────────────────────────────────
    (
        "ATL",
        "KATL",
        "Hartsfield-Jackson Atlanta International",
        "Atlanta",
        "United States",
        "US",
        33.6367,
        -84.4281,
    ),
    (
        "LAX",
        "KLAX",
        "Los Angeles International",
        "Los Angeles",
        "United States",
        "US",
        33.9425,
        -118.4081,
    ),
    (
        "ORD",
        "KORD",
        "O'Hare International",
        "Chicago",
        "United States",
        "US",
        41.9742,
        -87.9073,
    ),
    (
        "DFW",
        "KDFW",
        "Dallas/Fort Worth International",
        "Dallas",
        "United States",
        "US",
        32.8969,
        -97.0380,
    ),
    (
        "DEN",
        "KDEN",
        "Denver International",
        "Denver",
        "United States",
        "US",
        39.8561,
        -104.6737,
    ),
    (
        "JFK",
        "KJFK",
        "John F. Kennedy International",
        "New York",
        "United States",
        "US",
        40.6413,
        -73.7781,
    ),
    (
        "SFO",
        "KSFO",
        "San Francisco International",
        "San Francisco",
        "United States",
        "US",
        37.6213,
        -122.3790,
    ),
    (
        "SEA",
        "KSEA",
        "Seattle-Tacoma International",
        "Seattle",
        "United States",
        "US",
        47.4502,
        -122.3088,
    ),
    (
        "LAS",
        "KLAS",
        "Harry Reid International",
        "Las Vegas",
        "United States",
        "US",
        36.0840,
        -115.1537,
    ),
    (
        "MCO",
        "KMCO",
        "Orlando International",
        "Orlando",
        "United States",
        "US",
        28.4312,
        -81.3081,
    ),
    (
        "EWR",
        "KEWR",
        "Newark Liberty International",
        "Newark",
        "United States",
        "US",
        40.6895,
        -74.1745,
    ),
    (
        "MIA",
        "KMIA",
        "Miami International",
        "Miami",
        "United States",
        "US",
        25.7959,
        -80.2870,
    ),
    (
        "CLT",
        "KCLT",
        "Charlotte Douglas International",
        "Charlotte",
        "United States",
        "US",
        35.2140,
        -80.9431,
    ),
    (
        "PHX",
        "KPHX",
        "Phoenix Sky Harbor International",
        "Phoenix",
        "United States",
        "US",
        33.4373,
        -112.0078,
    ),
    (
        "IAH",
        "KIAH",
        "George Bush Intercontinental",
        "Houston",
        "United States",
        "US",
        29.9902,
        -95.3368,
    ),
    (
        "BOS",
        "KBOS",
        "Boston Logan International",
        "Boston",
        "United States",
        "US",
        42.3656,
        -71.0096,
    ),
    (
        "MSP",
        "KMSP",
        "Minneapolis-Saint Paul International",
        "Minneapolis",
        "United States",
        "US",
        44.8848,
        -93.2223,
    ),
    (
        "DTW",
        "KDTW",
        "Detroit Metropolitan Wayne County",
        "Detroit",
        "United States",
        "US",
        42.2162,
        -83.3554,
    ),
    (
        "PHL",
        "KPHL",
        "Philadelphia International",
        "Philadelphia",
        "United States",
        "US",
        39.8719,
        -75.2411,
    ),
    ("LGA", "KLGA", "LaGuardia", "New York", "United States", "US", 40.7772, -73.8726),
    (
        "IAD",
        "KIAD",
        "Washington Dulles International",
        "Washington D.C.",
        "United States",
        "US",
        38.9531,
        -77.4565,
    ),
    (
        "DCA",
        "KDCA",
        "Ronald Reagan Washington National",
        "Washington D.C.",
        "United States",
        "US",
        38.8512,
        -77.0402,
    ),
    (
        "BWI",
        "KBWI",
        "Baltimore/Washington International",
        "Baltimore",
        "United States",
        "US",
        39.1754,
        -76.6683,
    ),
    (
        "SLC",
        "KSLC",
        "Salt Lake City International",
        "Salt Lake City",
        "United States",
        "US",
        40.7884,
        -111.9778,
    ),
    (
        "SAN",
        "KSAN",
        "San Diego International",
        "San Diego",
        "United States",
        "US",
        32.7338,
        -117.1933,
    ),
    (
        "TPA",
        "KTPA",
        "Tampa International",
        "Tampa",
        "United States",
        "US",
        27.9755,
        -82.5332,
    ),
    (
        "AUS",
        "KAUS",
        "Austin-Bergstrom International",
        "Austin",
        "United States",
        "US",
        30.1945,
        -97.6699,
    ),
    (
        "PDX",
        "KPDX",
        "Portland International",
        "Portland",
        "United States",
        "US",
        45.5887,
        -122.5975,
    ),
    (
        "STL",
        "KSTL",
        "St. Louis Lambert International",
        "St. Louis",
        "United States",
        "US",
        38.7487,
        -90.3700,
    ),
    (
        "BNA",
        "KBNA",
        "Nashville International",
        "Nashville",
        "United States",
        "US",
        36.1245,
        -86.6782,
    ),
    (
        "MSY",
        "KMSY",
        "Louis Armstrong New Orleans International",
        "New Orleans",
        "United States",
        "US",
        29.9934,
        -90.2580,
    ),
    (
        "MCI",
        "KMCI",
        "Kansas City International",
        "Kansas City",
        "United States",
        "US",
        39.2976,
        -94.7139,
    ),
    (
        "RDU",
        "KRDU",
        "Raleigh-Durham International",
        "Raleigh",
        "United States",
        "US",
        35.8776,
        -78.7875,
    ),
    (
        "SMF",
        "KSMF",
        "Sacramento International",
        "Sacramento",
        "United States",
        "US",
        38.6954,
        -121.5908,
    ),
    (
        "SJC",
        "KSJC",
        "Norman Y. Mineta San José International",
        "San Jose",
        "United States",
        "US",
        37.3626,
        -121.9290,
    ),
    (
        "OAK",
        "KOAK",
        "Oakland International",
        "Oakland",
        "United States",
        "US",
        37.7213,
        -122.2208,
    ),
    (
        "MDW",
        "KMDW",
        "Chicago Midway International",
        "Chicago",
        "United States",
        "US",
        41.7868,
        -87.7522,
    ),
    (
        "HNL",
        "PHNL",
        "Daniel K. Inouye International",
        "Honolulu",
        "United States",
        "US",
        21.3187,
        -157.9224,
    ),
    (
        "ANC",
        "PANC",
        "Ted Stevens Anchorage International",
        "Anchorage",
        "United States",
        "US",
        61.1744,
        -149.9963,
    ),
    (
        "PIT",
        "KPIT",
        "Pittsburgh International",
        "Pittsburgh",
        "United States",
        "US",
        40.4915,
        -80.2329,
    ),
    (
        "IND",
        "KIND",
        "Indianapolis International",
        "Indianapolis",
        "United States",
        "US",
        39.7173,
        -86.2944,
    ),
    (
        "CMH",
        "KCMH",
        "John Glenn Columbus International",
        "Columbus",
        "United States",
        "US",
        39.9980,
        -82.8919,
    ),
    (
        "MKE",
        "KMKE",
        "Milwaukee Mitchell International",
        "Milwaukee",
        "United States",
        "US",
        42.9472,
        -87.8966,
    ),
    (
        "OMA",
        "KOMA",
        "Eppley Airfield",
        "Omaha",
        "United States",
        "US",
        41.3032,
        -95.8941,
    ),
    (
        "BUF",
        "KBUF",
        "Buffalo Niagara International",
        "Buffalo",
        "United States",
        "US",
        42.9405,
        -78.7322,
    ),
    (
        "ALB",
        "KALB",
        "Albany International",
        "Albany",
        "United States",
        "US",
        42.7483,
        -73.8017,
    ),
    (
        "BDL",
        "KBDL",
        "Bradley International",
        "Hartford",
        "United States",
        "US",
        41.9389,
        -72.6832,
    ),
    (
        "CLE",
        "KCLE",
        "Cleveland Hopkins International",
        "Cleveland",
        "United States",
        "US",
        41.4117,
        -81.8498,
    ),
    (
        "SJU",
        "TJSJ",
        "Luis Muñoz Marín International",
        "San Juan",
        "Puerto Rico",
        "PR",
        18.4394,
        -66.0018,
    ),
    (
        "HOU",
        "KHOU",
        "William P. Hobby",
        "Houston",
        "United States",
        "US",
        29.6454,
        -95.2789,
    ),
    (
        "DAL",
        "KDAL",
        "Dallas Love Field",
        "Dallas",
        "United States",
        "US",
        32.8471,
        -96.8518,
    ),
    (
        "ABQ",
        "KABQ",
        "Albuquerque International Sunport",
        "Albuquerque",
        "United States",
        "US",
        35.0402,
        -106.6090,
    ),
    (
        "OKC",
        "KOKC",
        "Will Rogers World",
        "Oklahoma City",
        "United States",
        "US",
        35.3931,
        -97.6007,
    ),
    (
        "MEM",
        "KMEM",
        "Memphis International",
        "Memphis",
        "United States",
        "US",
        35.0424,
        -89.9767,
    ),
    (
        "GRR",
        "KGRR",
        "Gerald R. Ford International",
        "Grand Rapids",
        "United States",
        "US",
        42.8808,
        -85.5228,
    ),
    (
        "TUL",
        "KTUL",
        "Tulsa International",
        "Tulsa",
        "United States",
        "US",
        36.1984,
        -95.8881,
    ),
    (
        "BOI",
        "KBOI",
        "Boise Airport",
        "Boise",
        "United States",
        "US",
        43.5644,
        -116.2228,
    ),
    (
        "ELP",
        "KELP",
        "El Paso International",
        "El Paso",
        "United States",
        "US",
        31.8072,
        -106.3779,
    ),
    (
        "LIT",
        "KLIT",
        "Bill and Hillary Clinton National",
        "Little Rock",
        "United States",
        "US",
        34.7294,
        -92.2243,
    ),
    (
        "JAN",
        "KJAN",
        "Jackson-Evers International",
        "Jackson",
        "United States",
        "US",
        32.3112,
        -90.0758,
    ),
    (
        "BHM",
        "KBHM",
        "Birmingham-Shuttlesworth International",
        "Birmingham",
        "United States",
        "US",
        33.5629,
        -86.7535,
    ),
    (
        "SDF",
        "KSDF",
        "Louisville Muhammad Ali International",
        "Louisville",
        "United States",
        "US",
        38.1744,
        -85.7360,
    ),
    (
        "LEX",
        "KLEX",
        "Blue Grass Airport",
        "Lexington",
        "United States",
        "US",
        38.0365,
        -84.6059,
    ),
    (
        "CHS",
        "KCHS",
        "Charleston International",
        "Charleston",
        "United States",
        "US",
        32.8986,
        -80.0405,
    ),
    (
        "SAV",
        "KSAV",
        "Savannah/Hilton Head International",
        "Savannah",
        "United States",
        "US",
        32.1276,
        -81.2021,
    ),
    (
        "JAX",
        "KJAX",
        "Jacksonville International",
        "Jacksonville",
        "United States",
        "US",
        30.4941,
        -81.6879,
    ),
    (
        "RSW",
        "KRSW",
        "Southwest Florida International",
        "Fort Myers",
        "United States",
        "US",
        26.5362,
        -81.7552,
    ),
    (
        "PBI",
        "KPBI",
        "Palm Beach International",
        "West Palm Beach",
        "United States",
        "US",
        26.6832,
        -80.0956,
    ),
    (
        "PWM",
        "KPWM",
        "Portland International Jetport",
        "Portland",
        "United States",
        "US",
        43.6462,
        -70.3093,
    ),
    (
        "ORF",
        "KORF",
        "Norfolk International",
        "Norfolk",
        "United States",
        "US",
        36.8976,
        -76.0133,
    ),
    (
        "RIC",
        "KRIC",
        "Richmond International",
        "Richmond",
        "United States",
        "US",
        37.5052,
        -77.3197,
    ),
    (
        "ROC",
        "KROC",
        "Greater Rochester International",
        "Rochester",
        "United States",
        "US",
        43.1189,
        -77.6724,
    ),
    (
        "SYR",
        "KSYR",
        "Syracuse Hancock International",
        "Syracuse",
        "United States",
        "US",
        43.1112,
        -76.1063,
    ),
    (
        "TYS",
        "KTYS",
        "McGhee Tyson Airport",
        "Knoxville",
        "United States",
        "US",
        35.8110,
        -83.9940,
    ),
    (
        "DSM",
        "KDSM",
        "Des Moines International",
        "Des Moines",
        "United States",
        "US",
        41.5340,
        -93.6631,
    ),
    (
        "GEG",
        "KGEG",
        "Spokane International",
        "Spokane",
        "United States",
        "US",
        47.6199,
        -117.5339,
    ),
    (
        "BZN",
        "KBZN",
        "Bozeman Yellowstone International",
        "Bozeman",
        "United States",
        "US",
        45.7775,
        -111.1530,
    ),
    (
        "FAI",
        "PAFA",
        "Fairbanks International",
        "Fairbanks",
        "United States",
        "US",
        64.8151,
        -147.8561,
    ),
    (
        "KOA",
        "PHKO",
        "Ellison Onizuka Kona International",
        "Kona",
        "United States",
        "US",
        19.7388,
        -156.0456,
    ),
    (
        "OGG",
        "PHOG",
        "Kahului Airport",
        "Maui",
        "United States",
        "US",
        20.8986,
        -156.4305,
    ),
    (
        "LIH",
        "PHLI",
        "Lihue Airport",
        "Lihue",
        "United States",
        "US",
        21.9760,
        -159.3390,
    ),
    (
        "GUM",
        "PGUM",
        "Antonio B. Won Pat International",
        "Guam",
        "Guam",
        "GU",
        13.4834,
        144.7958,
    ),
    (
        "BGR",
        "KBGR",
        "Bangor International",
        "Bangor",
        "United States",
        "US",
        44.8074,
        -68.8281,
    ),
    # ── Canada ─────────────────────────────────────────────────────────────
    (
        "YYZ",
        "CYYZ",
        "Toronto Pearson International",
        "Toronto",
        "Canada",
        "CA",
        43.6777,
        -79.6248,
    ),
    (
        "YVR",
        "CYVR",
        "Vancouver International",
        "Vancouver",
        "Canada",
        "CA",
        49.1947,
        -123.1792,
    ),
    (
        "YUL",
        "CYUL",
        "Montréal-Trudeau International",
        "Montreal",
        "Canada",
        "CA",
        45.4706,
        -73.7408,
    ),
    (
        "YYC",
        "CYYC",
        "Calgary International",
        "Calgary",
        "Canada",
        "CA",
        51.1315,
        -114.0106,
    ),
    (
        "YEG",
        "CYEG",
        "Edmonton International",
        "Edmonton",
        "Canada",
        "CA",
        53.3097,
        -113.5797,
    ),
    (
        "YOW",
        "CYOW",
        "Ottawa Macdonald-Cartier International",
        "Ottawa",
        "Canada",
        "CA",
        45.3225,
        -75.6692,
    ),
    (
        "YHZ",
        "CYHZ",
        "Halifax Stanfield International",
        "Halifax",
        "Canada",
        "CA",
        44.8808,
        -63.5086,
    ),
    (
        "YWG",
        "CYWG",
        "Winnipeg James Armstrong Richardson",
        "Winnipeg",
        "Canada",
        "CA",
        49.9100,
        -97.2398,
    ),
    (
        "YQB",
        "CYQB",
        "Québec City Jean Lesage International",
        "Quebec City",
        "Canada",
        "CA",
        46.7911,
        -71.3933,
    ),
    (
        "YXE",
        "CYXE",
        "Saskatoon John G. Diefenbaker International",
        "Saskatoon",
        "Canada",
        "CA",
        52.1708,
        -106.6993,
    ),
    (
        "YYJ",
        "CYYJ",
        "Victoria International",
        "Victoria",
        "Canada",
        "CA",
        48.6469,
        -123.4258,
    ),
    # ── Mexico & Central America ────────────────────────────────────────────
    (
        "MEX",
        "MMMX",
        "Benito Juárez International",
        "Mexico City",
        "Mexico",
        "MX",
        19.4363,
        -99.0721,
    ),
    (
        "CUN",
        "MMUN",
        "Cancún International",
        "Cancun",
        "Mexico",
        "MX",
        21.0365,
        -86.8771,
    ),
    (
        "GDL",
        "MMGL",
        "Miguel Hidalgo y Costilla International",
        "Guadalajara",
        "Mexico",
        "MX",
        20.5218,
        -103.3106,
    ),
    (
        "MTY",
        "MMMY",
        "General Mariano Escobedo International",
        "Monterrey",
        "Mexico",
        "MX",
        25.7749,
        -100.1069,
    ),
    (
        "SJD",
        "MMSD",
        "Los Cabos International",
        "San Jose del Cabo",
        "Mexico",
        "MX",
        23.1518,
        -109.7211,
    ),
    (
        "PVR",
        "MMPR",
        "Licenciado Gustavo Díaz Ordaz International",
        "Puerto Vallarta",
        "Mexico",
        "MX",
        20.6801,
        -105.2544,
    ),
    (
        "MZT",
        "MMMZ",
        "General Rafael Buelna International",
        "Mazatlan",
        "Mexico",
        "MX",
        23.1614,
        -106.2659,
    ),
    (
        "ACA",
        "MMAA",
        "Juan N. Álvarez International",
        "Acapulco",
        "Mexico",
        "MX",
        16.7571,
        -99.7540,
    ),
    (
        "OAX",
        "MMOX",
        "Xoxocotlán International",
        "Oaxaca",
        "Mexico",
        "MX",
        16.9999,
        -96.7260,
    ),
    (
        "PTY",
        "MPTO",
        "Tocumen International",
        "Panama City",
        "Panama",
        "PA",
        9.0714,
        -79.3835,
    ),
    (
        "SJO",
        "MROC",
        "Juan Santamaría International",
        "San Jose",
        "Costa Rica",
        "CR",
        9.9939,
        -84.2088,
    ),
    (
        "GUA",
        "MGGT",
        "La Aurora International",
        "Guatemala City",
        "Guatemala",
        "GT",
        14.5833,
        -90.5275,
    ),
    (
        "SAL",
        "MSLP",
        "Monseñor Óscar Arnulfo Romero International",
        "San Salvador",
        "El Salvador",
        "SV",
        13.4409,
        -89.0557,
    ),
    (
        "MGA",
        "MNMG",
        "Augusto C. Sandino International",
        "Managua",
        "Nicaragua",
        "NI",
        12.1415,
        -86.1682,
    ),
    (
        "RTB",
        "MHNJ",
        "Juan Manuel Gálvez International",
        "Roatan",
        "Honduras",
        "HN",
        16.3168,
        -86.5230,
    ),
    (
        "TGU",
        "MHTG",
        "Toncontín International",
        "Tegucigalpa",
        "Honduras",
        "HN",
        14.0608,
        -87.2172,
    ),
    (
        "BZE",
        "MZBZ",
        "Philip S. W. Goldson International",
        "Belize City",
        "Belize",
        "BZ",
        17.5391,
        -88.3082,
    ),
    # ── Caribbean ──────────────────────────────────────────────────────────
    (
        "HAV",
        "MUHA",
        "José Martí International",
        "Havana",
        "Cuba",
        "CU",
        22.9892,
        -82.4091,
    ),
    (
        "SDQ",
        "MDSD",
        "Las Américas International",
        "Santo Domingo",
        "Dominican Republic",
        "DO",
        18.4297,
        -69.6689,
    ),
    (
        "PUJ",
        "MDPC",
        "Punta Cana International",
        "Punta Cana",
        "Dominican Republic",
        "DO",
        18.5674,
        -68.3634,
    ),
    (
        "MBJ",
        "MKJS",
        "Sangster International",
        "Montego Bay",
        "Jamaica",
        "JM",
        18.5037,
        -77.9134,
    ),
    (
        "KIN",
        "MKJP",
        "Norman Manley International",
        "Kingston",
        "Jamaica",
        "JM",
        17.9357,
        -76.7875,
    ),
    (
        "BGI",
        "TBPB",
        "Grantley Adams International",
        "Bridgetown",
        "Barbados",
        "BB",
        13.0746,
        -59.4925,
    ),
    (
        "POS",
        "TTPP",
        "Piarco International",
        "Port of Spain",
        "Trinidad and Tobago",
        "TT",
        10.5954,
        -61.3372,
    ),
    (
        "AUA",
        "TNCA",
        "Queen Beatrix International",
        "Oranjestad",
        "Aruba",
        "AW",
        12.5014,
        -70.0152,
    ),
    (
        "CUR",
        "TNCC",
        "Hato International",
        "Willemstad",
        "Curaçao",
        "CW",
        12.1889,
        -68.9598,
    ),
    (
        "SXM",
        "TNCM",
        "Princess Juliana International",
        "Sint Maarten",
        "Sint Maarten",
        "SX",
        18.0410,
        -63.1089,
    ),
    (
        "GCM",
        "MWCR",
        "Owen Roberts International",
        "George Town",
        "Cayman Islands",
        "KY",
        19.2928,
        -81.3577,
    ),
    (
        "NAS",
        "MYNN",
        "Lynden Pindling International",
        "Nassau",
        "Bahamas",
        "BS",
        25.0389,
        -77.4662,
    ),
    # ── South America ──────────────────────────────────────────────────────
    (
        "GRU",
        "SBGR",
        "São Paulo/Guarulhos International",
        "Sao Paulo",
        "Brazil",
        "BR",
        -23.4356,
        -46.4731,
    ),
    (
        "GIG",
        "SBGL",
        "Rio de Janeiro/Galeão International",
        "Rio de Janeiro",
        "Brazil",
        "BR",
        -22.8100,
        -43.2506,
    ),
    (
        "SDU",
        "SBRJ",
        "Santos Dumont Airport",
        "Rio de Janeiro",
        "Brazil",
        "BR",
        -22.9105,
        -43.1631,
    ),
    (
        "CGH",
        "SBSP",
        "Congonhas Airport",
        "Sao Paulo",
        "Brazil",
        "BR",
        -23.6261,
        -46.6558,
    ),
    (
        "BSB",
        "SBBR",
        "Brasilia International",
        "Brasilia",
        "Brazil",
        "BR",
        -15.8711,
        -47.9186,
    ),
    (
        "SSA",
        "SBSV",
        "Deputado Luís Eduardo Magalhães International",
        "Salvador",
        "Brazil",
        "BR",
        -12.9086,
        -38.3225,
    ),
    (
        "FOR",
        "SBFZ",
        "Pinto Martins International",
        "Fortaleza",
        "Brazil",
        "BR",
        -3.7763,
        -38.5326,
    ),
    (
        "REC",
        "SBRF",
        "Guararapes International",
        "Recife",
        "Brazil",
        "BR",
        -8.1265,
        -34.9231,
    ),
    (
        "BEL",
        "SBBE",
        "Val de Cans International",
        "Belem",
        "Brazil",
        "BR",
        -1.3792,
        -48.4763,
    ),
    (
        "MAO",
        "SBEG",
        "Eduardo Gomes International",
        "Manaus",
        "Brazil",
        "BR",
        -3.0386,
        -60.0498,
    ),
    (
        "EZE",
        "SAEZ",
        "Ministro Pistarini International (Ezeiza)",
        "Buenos Aires",
        "Argentina",
        "AR",
        -34.8222,
        -58.5358,
    ),
    (
        "AEP",
        "SABE",
        "Jorge Newbery Airpark",
        "Buenos Aires",
        "Argentina",
        "AR",
        -34.5592,
        -58.4156,
    ),
    (
        "COR",
        "SACO",
        "Ingeniero Ambrosio L.V. Taravella International",
        "Cordoba",
        "Argentina",
        "AR",
        -31.3236,
        -64.2080,
    ),
    (
        "SCL",
        "SCEL",
        "Arturo Merino Benítez International",
        "Santiago",
        "Chile",
        "CL",
        -33.3930,
        -70.7858,
    ),
    (
        "BOG",
        "SKBO",
        "El Dorado International",
        "Bogota",
        "Colombia",
        "CO",
        4.7016,
        -74.1469,
    ),
    (
        "MDE",
        "SKRG",
        "José María Córdova International",
        "Medellin",
        "Colombia",
        "CO",
        6.1645,
        -75.4231,
    ),
    (
        "CTG",
        "SKCG",
        "Rafael Núñez International",
        "Cartagena",
        "Colombia",
        "CO",
        10.4424,
        -75.5130,
    ),
    (
        "LIM",
        "SPJC",
        "Jorge Chávez International",
        "Lima",
        "Peru",
        "PE",
        -12.0219,
        -77.1143,
    ),
    (
        "CUZ",
        "SPZO",
        "Alejandro Velasco Astete International",
        "Cusco",
        "Peru",
        "PE",
        -13.5357,
        -71.9388,
    ),
    (
        "UIO",
        "SEQM",
        "Mariscal Sucre International",
        "Quito",
        "Ecuador",
        "EC",
        -0.1292,
        -78.3576,
    ),
    (
        "GYE",
        "SEGU",
        "José Joaquín de Olmedo International",
        "Guayaquil",
        "Ecuador",
        "EC",
        -2.1574,
        -79.8836,
    ),
    (
        "CCS",
        "SVMI",
        "Simón Bolívar International",
        "Caracas",
        "Venezuela",
        "VE",
        10.6031,
        -66.9913,
    ),
    (
        "MVD",
        "SUAA",
        "Carrasco International",
        "Montevideo",
        "Uruguay",
        "UY",
        -34.8384,
        -56.0308,
    ),
    (
        "ASU",
        "SGAS",
        "Silvio Pettirossi International",
        "Asuncion",
        "Paraguay",
        "PY",
        -25.2400,
        -57.5198,
    ),
    (
        "VVI",
        "SLVR",
        "Viru Viru International",
        "Santa Cruz",
        "Bolivia",
        "BO",
        -17.6448,
        -63.1354,
    ),
    (
        "LPB",
        "SLLP",
        "El Alto International",
        "La Paz",
        "Bolivia",
        "BO",
        -16.5133,
        -68.1923,
    ),
    (
        "PBM",
        "SMJP",
        "Johan Adolf Pengel International",
        "Paramaribo",
        "Suriname",
        "SR",
        5.4528,
        -55.1878,
    ),
    (
        "GEO",
        "SYCJ",
        "Cheddi Jagan International",
        "Georgetown",
        "Guyana",
        "GY",
        6.4985,
        -58.2541,
    ),
    # ── United Kingdom ──────────────────────────────────────────────────────
    (
        "LHR",
        "EGLL",
        "London Heathrow",
        "London",
        "United Kingdom",
        "GB",
        51.4775,
        -0.4614,
    ),
    (
        "LGW",
        "EGKK",
        "London Gatwick",
        "London",
        "United Kingdom",
        "GB",
        51.1481,
        -0.1903,
    ),
    (
        "STN",
        "EGSS",
        "London Stansted",
        "London",
        "United Kingdom",
        "GB",
        51.8850,
        0.2350,
    ),
    ("LTN", "EGGW", "London Luton", "London", "United Kingdom", "GB", 51.8747, -0.3683),
    ("LCY", "EGLC", "London City", "London", "United Kingdom", "GB", 51.5053, 0.0553),
    (
        "MAN",
        "EGCC",
        "Manchester",
        "Manchester",
        "United Kingdom",
        "GB",
        53.3537,
        -2.2750,
    ),
    (
        "BHX",
        "EGBB",
        "Birmingham",
        "Birmingham",
        "United Kingdom",
        "GB",
        52.4539,
        -1.7480,
    ),
    ("EDI", "EGPH", "Edinburgh", "Edinburgh", "United Kingdom", "GB", 55.9500, -3.3725),
    ("GLA", "EGPF", "Glasgow", "Glasgow", "United Kingdom", "GB", 55.8719, -4.4331),
    ("BRS", "EGGD", "Bristol", "Bristol", "United Kingdom", "GB", 51.3827, -2.7191),
    (
        "LPL",
        "EGGP",
        "Liverpool John Lennon",
        "Liverpool",
        "United Kingdom",
        "GB",
        53.3336,
        -2.8497,
    ),
    ("NCL", "EGNT", "Newcastle", "Newcastle", "United Kingdom", "GB", 54.9375, -1.6917),
    (
        "BFS",
        "EGAA",
        "Belfast International",
        "Belfast",
        "United Kingdom",
        "GB",
        54.6575,
        -6.2158,
    ),
    ("ABZ", "EGPD", "Aberdeen", "Aberdeen", "United Kingdom", "GB", 57.2019, -2.1978),
    (
        "EXT",
        "EGTE",
        "Exeter International",
        "Exeter",
        "United Kingdom",
        "GB",
        50.7344,
        -3.4139,
    ),
    # ── Ireland ────────────────────────────────────────────────────────────
    ("DUB", "EIDW", "Dublin", "Dublin", "Ireland", "IE", 53.4213, -6.2700),
    ("ORK", "EICK", "Cork", "Cork", "Ireland", "IE", 51.8413, -8.4911),
    ("SNN", "EINN", "Shannon", "Shannon", "Ireland", "IE", 52.7020, -8.9248),
    # ── France ─────────────────────────────────────────────────────────────
    (
        "CDG",
        "LFPG",
        "Paris Charles de Gaulle",
        "Paris",
        "France",
        "FR",
        49.0097,
        2.5479,
    ),
    ("ORY", "LFPO", "Paris Orly", "Paris", "France", "FR", 48.7233, 2.3794),
    ("NCE", "LFMN", "Nice Côte d'Azur", "Nice", "France", "FR", 43.6584, 7.2159),
    ("LYS", "LFLL", "Lyon-Saint Exupéry", "Lyon", "France", "FR", 45.7256, 5.0811),
    ("MRS", "LFML", "Marseille Provence", "Marseille", "France", "FR", 43.4393, 5.2214),
    ("TLS", "LFBO", "Toulouse-Blagnac", "Toulouse", "France", "FR", 43.6293, 1.3678),
    ("BOD", "LFBD", "Bordeaux-Mérignac", "Bordeaux", "France", "FR", 44.8283, -0.7155),
    ("NTE", "LFRS", "Nantes Atlantique", "Nantes", "France", "FR", 47.1532, -1.6108),
    ("SXB", "LFST", "Strasbourg", "Strasbourg", "France", "FR", 48.5383, 7.6283),
    ("BIA", "LFKB", "Bastia-Poretta", "Bastia", "France", "FR", 42.5527, 9.4837),
    (
        "AJA",
        "LFKJ",
        "Ajaccio Napoleon Bonaparte",
        "Ajaccio",
        "France",
        "FR",
        41.9236,
        8.8026,
    ),
    # ── Germany ────────────────────────────────────────────────────────────
    ("FRA", "EDDF", "Frankfurt am Main", "Frankfurt", "Germany", "DE", 50.0379, 8.5622),
    (
        "MUC",
        "EDDM",
        "Munich Franz Josef Strauss",
        "Munich",
        "Germany",
        "DE",
        48.3538,
        11.7861,
    ),
    ("BER", "EDDB", "Berlin Brandenburg", "Berlin", "Germany", "DE", 52.3667, 13.5033),
    ("DUS", "EDDL", "Düsseldorf", "Dusseldorf", "Germany", "DE", 51.2895, 6.7668),
    ("HAM", "EDDH", "Hamburg", "Hamburg", "Germany", "DE", 53.6304, 9.9882),
    ("STR", "EDDS", "Stuttgart", "Stuttgart", "Germany", "DE", 48.6899, 9.2220),
    ("CGN", "EDDK", "Cologne Bonn", "Cologne", "Germany", "DE", 50.8659, 7.1427),
    ("NUE", "EDDN", "Nuremberg", "Nuremberg", "Germany", "DE", 49.4987, 11.0669),
    ("HAJ", "EDDV", "Hanover", "Hanover", "Germany", "DE", 52.4611, 9.6850),
    ("LEJ", "EDDP", "Leipzig/Halle", "Leipzig", "Germany", "DE", 51.4324, 12.2162),
    ("DRS", "EDDC", "Dresden", "Dresden", "Germany", "DE", 51.1328, 13.7672),
    ("BRE", "EDDW", "Bremen", "Bremen", "Germany", "DE", 53.0475, 8.7867),
    # ── Netherlands & Belgium ───────────────────────────────────────────────
    (
        "AMS",
        "EHAM",
        "Amsterdam Schiphol",
        "Amsterdam",
        "Netherlands",
        "NL",
        52.3105,
        4.7683,
    ),
    ("EIN", "EHEH", "Eindhoven", "Eindhoven", "Netherlands", "NL", 51.4501, 5.3746),
    ("BRU", "EBBR", "Brussels", "Brussels", "Belgium", "BE", 50.9014, 4.4844),
    (
        "CRL",
        "EBCI",
        "Brussels South Charleroi",
        "Charleroi",
        "Belgium",
        "BE",
        50.4592,
        4.4538,
    ),
    ("LGG", "EBLG", "Liège", "Liege", "Belgium", "BE", 50.6374, 5.4432),
    # ── Spain & Portugal ────────────────────────────────────────────────────
    (
        "MAD",
        "LEMD",
        "Adolfo Suárez Madrid-Barajas",
        "Madrid",
        "Spain",
        "ES",
        40.4719,
        -3.5626,
    ),
    ("BCN", "LEBL", "Barcelona-El Prat", "Barcelona", "Spain", "ES", 41.2971, 2.0785),
    ("AGP", "LEMG", "Málaga-Costa del Sol", "Malaga", "Spain", "ES", 36.6749, -4.4991),
    ("PMI", "LEPA", "Palma de Mallorca", "Palma", "Spain", "ES", 39.5517, 2.7388),
    ("LPA", "GCLP", "Gran Canaria", "Las Palmas", "Spain", "ES", 27.9319, -15.3866),
    ("TFS", "GCTS", "Tenerife South", "Tenerife", "Spain", "ES", 28.0445, -16.5725),
    (
        "TFN",
        "GCXO",
        "Tenerife North Los Rodeos",
        "Tenerife",
        "Spain",
        "ES",
        28.4827,
        -16.3414,
    ),
    ("ALC", "LEAL", "Alicante-Elche", "Alicante", "Spain", "ES", 38.2822, -0.5582),
    ("VLC", "LEVC", "Valencia", "Valencia", "Spain", "ES", 39.4893, -0.4816),
    ("BIO", "LEBB", "Bilbao", "Bilbao", "Spain", "ES", 43.3011, -2.9106),
    ("SVQ", "LEZL", "Seville", "Seville", "Spain", "ES", 37.4180, -5.8931),
    (
        "SCQ",
        "LEST",
        "Santiago de Compostela",
        "Santiago de Compostela",
        "Spain",
        "ES",
        42.8963,
        -8.4151,
    ),
    ("ACE", "GCRR", "Lanzarote", "Arrecife", "Spain", "ES", 28.9455, -13.6052),
    (
        "FUE",
        "GCFV",
        "Fuerteventura",
        "Puerto del Rosario",
        "Spain",
        "ES",
        28.4527,
        -13.8638,
    ),
    ("MAH", "LEMH", "Menorca", "Mahon", "Spain", "ES", 39.8626, 4.2186),
    ("IBZ", "LEIB", "Ibiza", "Ibiza", "Spain", "ES", 38.8729, 1.3731),
    ("GRO", "LEGE", "Girona-Costa Brava", "Girona", "Spain", "ES", 41.9010, 2.7605),
    ("REU", "LERS", "Reus", "Reus", "Spain", "ES", 41.1474, 1.1672),
    (
        "LIS",
        "LPPT",
        "Humberto Delgado (Lisbon Portela)",
        "Lisbon",
        "Portugal",
        "PT",
        38.7756,
        -9.1354,
    ),
    (
        "OPO",
        "LPPR",
        "Francisco de Sá Carneiro (Porto)",
        "Porto",
        "Portugal",
        "PT",
        41.2481,
        -8.6814,
    ),
    ("FAO", "LPFR", "Faro", "Faro", "Portugal", "PT", 37.0144, -7.9659),
    ("FNC", "LPMA", "Madeira", "Funchal", "Portugal", "PT", 32.6979, -16.7745),
    (
        "PDL",
        "LPPD",
        "João Paulo II (Ponta Delgada)",
        "Ponta Delgada",
        "Portugal",
        "PT",
        37.7412,
        -25.6979,
    ),
    # ── Italy ──────────────────────────────────────────────────────────────
    (
        "FCO",
        "LIRF",
        "Rome Fiumicino (Leonardo da Vinci)",
        "Rome",
        "Italy",
        "IT",
        41.7999,
        12.2462,
    ),
    ("CIA", "LIRA", "Rome Ciampino", "Rome", "Italy", "IT", 41.7994, 12.5949),
    ("MXP", "LIMC", "Milan Malpensa", "Milan", "Italy", "IT", 45.6306, 8.7231),
    ("LIN", "LIML", "Milan Linate", "Milan", "Italy", "IT", 45.4454, 9.2767),
    (
        "BGY",
        "LIME",
        "Milan Bergamo (Orio al Serio)",
        "Bergamo",
        "Italy",
        "IT",
        45.6739,
        9.7040,
    ),
    ("VCE", "LIPZ", "Venice Marco Polo", "Venice", "Italy", "IT", 45.5053, 12.3519),
    ("NAP", "LIRN", "Naples", "Naples", "Italy", "IT", 40.8860, 14.2908),
    ("PSA", "LIRP", "Pisa (Galileo Galilei)", "Pisa", "Italy", "IT", 43.6839, 10.3927),
    (
        "FLR",
        "LIRQ",
        "Florence (Amerigo Vespucci)",
        "Florence",
        "Italy",
        "IT",
        43.8099,
        11.2051,
    ),
    ("BRI", "LIBD", "Bari (Karol Wojtyła)", "Bari", "Italy", "IT", 41.1389, 16.7606),
    (
        "CTA",
        "LICC",
        "Catania-Fontanarossa (Vincenzo Bellini)",
        "Catania",
        "Italy",
        "IT",
        37.4668,
        15.0664,
    ),
    (
        "PMO",
        "LICJ",
        "Palermo (Falcone-Borsellino)",
        "Palermo",
        "Italy",
        "IT",
        38.1759,
        13.0910,
    ),
    ("CAG", "LIEE", "Cagliari Elmas", "Cagliari", "Italy", "IT", 39.2515, 9.0543),
    (
        "BLQ",
        "LIPE",
        "Bologna Guglielmo Marconi",
        "Bologna",
        "Italy",
        "IT",
        44.5354,
        11.2887,
    ),
    ("TRN", "LIMF", "Turin (Sandro Pertini)", "Turin", "Italy", "IT", 45.2006, 7.6497),
    # ── Switzerland & Austria ───────────────────────────────────────────────
    ("ZRH", "LSZH", "Zurich", "Zurich", "Switzerland", "CH", 47.4647, 8.5492),
    ("GVA", "LSGG", "Geneva", "Geneva", "Switzerland", "CH", 46.2381, 6.1089),
    (
        "BSL",
        "LFSB",
        "EuroAirport Basel Mulhouse Freiburg",
        "Basel",
        "Switzerland",
        "CH",
        47.5896,
        7.5299,
    ),
    ("BRN", "LSZB", "Bern Belp", "Bern", "Switzerland", "CH", 46.9141, 7.4971),
    (
        "VIE",
        "LOWW",
        "Vienna International",
        "Vienna",
        "Austria",
        "AT",
        48.1103,
        16.5697,
    ),
    ("GRZ", "LOWG", "Graz", "Graz", "Austria", "AT", 46.9911, 15.4396),
    ("SZG", "LOWS", "Salzburg", "Salzburg", "Austria", "AT", 47.7933, 13.0043),
    ("INN", "LOWI", "Innsbruck", "Innsbruck", "Austria", "AT", 47.2602, 11.3440),
    # ── Scandinavia ────────────────────────────────────────────────────────
    ("CPH", "EKCH", "Copenhagen", "Copenhagen", "Denmark", "DK", 55.6180, 12.6560),
    ("OSL", "ENGM", "Oslo Gardermoen", "Oslo", "Norway", "NO", 60.1939, 11.1004),
    ("ARN", "ESSA", "Stockholm Arlanda", "Stockholm", "Sweden", "SE", 59.6519, 17.9186),
    (
        "GOT",
        "ESGG",
        "Gothenburg Landvetter",
        "Gothenburg",
        "Sweden",
        "SE",
        57.6628,
        12.2798,
    ),
    ("HEL", "EFHK", "Helsinki Vantaa", "Helsinki", "Finland", "FI", 60.3172, 24.9633),
    ("RVN", "EFRO", "Rovaniemi", "Rovaniemi", "Finland", "FI", 66.5648, 25.8304),
    ("BGO", "ENBR", "Bergen Flesland", "Bergen", "Norway", "NO", 60.2934, 5.2181),
    ("TRD", "ENVA", "Trondheim Værnes", "Trondheim", "Norway", "NO", 63.4578, 10.9260),
    ("RKV", "BIRK", "Reykjavík", "Reykjavik", "Iceland", "IS", 64.1299, -21.9406),
    (
        "KEF",
        "BIKF",
        "Keflavik International",
        "Reykjavik",
        "Iceland",
        "IS",
        63.9850,
        -22.6056,
    ),
    ("BLL", "EKBI", "Billund", "Billund", "Denmark", "DK", 55.7403, 9.1518),
    ("AAL", "EKYT", "Aalborg", "Aalborg", "Denmark", "DK", 57.0928, 9.8492),
    (
        "FAE",
        "EKVG",
        "Vágar (Faroe Islands)",
        "Torshavn",
        "Faroe Islands",
        "FO",
        62.0636,
        -7.2772,
    ),
    ("AES", "ENAL", "Ålesund Vigra", "Ålesund", "Norway", "NO", 62.5625, 6.1197),
    ("SVG", "ENZV", "Stavanger Sola", "Stavanger", "Norway", "NO", 58.8768, 5.6378),
    ("BOO", "ENBO", "Bodø", "Bodo", "Norway", "NO", 67.2692, 14.3653),
    ("TOS", "ENTC", "Tromsø Langnes", "Tromso", "Norway", "NO", 69.6833, 18.9188),
    ("LYR", "ENSB", "Svalbard", "Longyearbyen", "Norway", "NO", 78.2462, 15.4656),
    ("VXO", "ESMX", "Växjö Kronoberg", "Vaxjo", "Sweden", "SE", 56.9291, 14.7280),
    ("VBY", "ESVS", "Visby", "Visby", "Sweden", "SE", 57.6628, 18.3462),
    ("MMX", "ESMS", "Malmö", "Malmo", "Sweden", "SE", 55.5363, 13.3762),
    ("OUL", "EFOU", "Oulu", "Oulu", "Finland", "FI", 64.9301, 25.3546),
    ("TMP", "EFTP", "Tampere-Pirkkala", "Tampere", "Finland", "FI", 61.4141, 23.6044),
    ("TKU", "EFTU", "Turku", "Turku", "Finland", "FI", 60.5141, 22.2628),
    ("KTT", "EFKT", "Kittila", "Kittila", "Finland", "FI", 67.7010, 24.8468),
    # ── Eastern Europe ─────────────────────────────────────────────────────
    ("WAW", "EPWA", "Warsaw Chopin", "Warsaw", "Poland", "PL", 52.1657, 20.9671),
    (
        "KRK",
        "EPKK",
        "Kraków John Paul II International",
        "Krakow",
        "Poland",
        "PL",
        50.0777,
        19.7848,
    ),
    (
        "PRG",
        "LKPR",
        "Václav Havel Prague",
        "Prague",
        "Czech Republic",
        "CZ",
        50.1008,
        14.2600,
    ),
    (
        "BUD",
        "LHBP",
        "Budapest Ferenc Liszt International",
        "Budapest",
        "Hungary",
        "HU",
        47.4298,
        19.2611,
    ),
    (
        "BEG",
        "LYBE",
        "Belgrade Nikola Tesla",
        "Belgrade",
        "Serbia",
        "RS",
        44.8184,
        20.3091,
    ),
    (
        "OTP",
        "LROP",
        "Henri Coandă (Bucharest)",
        "Bucharest",
        "Romania",
        "RO",
        44.5711,
        26.0858,
    ),
    ("SOF", "LBSF", "Sofia", "Sofia", "Bulgaria", "BG", 42.6967, 23.4114),
    ("ZAG", "LDZA", "Zagreb", "Zagreb", "Croatia", "HR", 45.7429, 16.0688),
    ("DBV", "LDDU", "Dubrovnik", "Dubrovnik", "Croatia", "HR", 42.5614, 18.2682),
    ("SPU", "LDSP", "Split", "Split", "Croatia", "HR", 43.5390, 16.2980),
    (
        "LJU",
        "LJLJ",
        "Ljubljana Jože Pučnik",
        "Ljubljana",
        "Slovenia",
        "SI",
        46.2237,
        14.4576,
    ),
    ("SKP", "LWSK", "Skopje", "Skopje", "North Macedonia", "MK", 41.9616, 21.6214),
    (
        "TIA",
        "LATI",
        "Tirana Mother Teresa",
        "Tirana",
        "Albania",
        "AL",
        41.4147,
        19.7206,
    ),
    (
        "SJJ",
        "LQSA",
        "Sarajevo",
        "Sarajevo",
        "Bosnia and Herzegovina",
        "BA",
        43.8246,
        18.3315,
    ),
    ("PDV", "LBPD", "Plovdiv", "Plovdiv", "Bulgaria", "BG", 42.0678, 24.8508),
    (
        "CLJ",
        "LRCL",
        "Cluj-Napoca Avram Iancu International",
        "Cluj-Napoca",
        "Romania",
        "RO",
        46.7852,
        23.6862,
    ),
    ("RJK", "LDRI", "Rijeka", "Rijeka", "Croatia", "HR", 45.2169, 14.5703),
    ("PUY", "LDPL", "Pula", "Pula", "Croatia", "HR", 44.8935, 13.9222),
    ("ZAD", "LDZD", "Zadar", "Zadar", "Croatia", "HR", 44.1083, 15.3467),
    ("TGD", "LYPG", "Podgorica", "Podgorica", "Montenegro", "ME", 42.3594, 19.2519),
    (
        "PRN",
        "BKPR",
        "Pristina Adem Jashari International",
        "Pristina",
        "Kosovo",
        "XK",
        42.5728,
        21.0358,
    ),
    # ── Baltic States ──────────────────────────────────────────────────────
    ("RIX", "EVRA", "Riga International", "Riga", "Latvia", "LV", 56.9236, 23.9711),
    ("TLL", "EETN", "Tallinn", "Tallinn", "Estonia", "EE", 59.4133, 24.8328),
    ("VNO", "EYVI", "Vilnius", "Vilnius", "Lithuania", "LT", 54.6341, 25.2858),
    # ── More Europe ────────────────────────────────────────────────────────
    (
        "LUX",
        "ELLX",
        "Luxembourg Findel",
        "Luxembourg City",
        "Luxembourg",
        "LU",
        49.6233,
        6.2044,
    ),
    ("MSQ", "UMMS", "Minsk International", "Minsk", "Belarus", "BY", 53.8825, 28.0307),
    (
        "KIV",
        "LUKK",
        "Chișinău International",
        "Chisinau",
        "Moldova",
        "MD",
        46.9277,
        28.9313,
    ),
    (
        "KBP",
        "UKBB",
        "Boryspil International",
        "Kiev",
        "Ukraine",
        "UA",
        50.3450,
        30.8947,
    ),
    (
        "IEV",
        "UKKK",
        "Kyiv Igor Sikorsky International",
        "Kiev",
        "Ukraine",
        "UA",
        50.4016,
        30.4497,
    ),
    (
        "LWO",
        "UKLL",
        "Lviv Danylo Halytskyi International",
        "Lviv",
        "Ukraine",
        "UA",
        49.8125,
        23.9561,
    ),
    (
        "ODS",
        "UKOO",
        "Odessa International",
        "Odessa",
        "Ukraine",
        "UA",
        46.4268,
        30.6765,
    ),
    # ── Russia & CIS ───────────────────────────────────────────────────────
    ("SVO", "UUEE", "Moscow Sheremetyevo", "Moscow", "Russia", "RU", 55.9726, 37.4146),
    ("DME", "UUDD", "Moscow Domodedovo", "Moscow", "Russia", "RU", 55.4088, 37.9063),
    ("VKO", "UUWW", "Moscow Vnukovo", "Moscow", "Russia", "RU", 55.5915, 37.2615),
    (
        "LED",
        "ULLI",
        "St. Petersburg Pulkovo",
        "St. Petersburg",
        "Russia",
        "RU",
        59.8003,
        30.2625,
    ),
    (
        "OVB",
        "UNNT",
        "Novosibirsk Tolmachevo",
        "Novosibirsk",
        "Russia",
        "RU",
        55.0126,
        82.6507,
    ),
    (
        "KJA",
        "UNKL",
        "Krasnoyarsk Yemelyanovo",
        "Krasnoyarsk",
        "Russia",
        "RU",
        56.1729,
        92.4933,
    ),
    ("IKT", "UIII", "Irkutsk", "Irkutsk", "Russia", "RU", 52.2680, 104.3889),
    (
        "VVO",
        "UHWW",
        "Vladivostok International",
        "Vladivostok",
        "Russia",
        "RU",
        43.3990,
        132.1479,
    ),
    (
        "ALA",
        "UAAA",
        "Almaty International",
        "Almaty",
        "Kazakhstan",
        "KZ",
        43.3521,
        77.0405,
    ),
    (
        "NQZ",
        "UACC",
        "Nursultan Nazarbayev International",
        "Astana",
        "Kazakhstan",
        "KZ",
        51.0223,
        71.4669,
    ),
    (
        "TAS",
        "UTTT",
        "Islam Karimov Tashkent International",
        "Tashkent",
        "Uzbekistan",
        "UZ",
        41.2579,
        69.2812,
    ),
    (
        "GYD",
        "UBBB",
        "Heydar Aliyev International",
        "Baku",
        "Azerbaijan",
        "AZ",
        40.4675,
        50.0467,
    ),
    (
        "TBS",
        "UGTB",
        "Tbilisi International",
        "Tbilisi",
        "Georgia",
        "GE",
        41.6692,
        44.9547,
    ),
    (
        "EVN",
        "UDYZ",
        "Zvartnots International",
        "Yerevan",
        "Armenia",
        "AM",
        40.1473,
        44.3959,
    ),
    (
        "FRU",
        "UAFM",
        "Manas International",
        "Bishkek",
        "Kyrgyzstan",
        "KG",
        43.0612,
        74.4776,
    ),
    (
        "ASB",
        "UTAA",
        "Ashgabat International",
        "Ashgabat",
        "Turkmenistan",
        "TM",
        37.9864,
        58.3610,
    ),
    (
        "DYU",
        "UTDD",
        "Dushanbe International",
        "Dushanbe",
        "Tajikistan",
        "TJ",
        38.5433,
        68.8250,
    ),
    # ── Greece & Cyprus ────────────────────────────────────────────────────
    (
        "ATH",
        "LGAV",
        "Athens Eleftherios Venizelos",
        "Athens",
        "Greece",
        "GR",
        37.9364,
        23.9445,
    ),
    (
        "SKG",
        "LGTS",
        "Thessaloniki Macedonia",
        "Thessaloniki",
        "Greece",
        "GR",
        40.5197,
        22.9709,
    ),
    (
        "HER",
        "LGIR",
        "Heraklion Nikos Kazantzakis",
        "Heraklion",
        "Greece",
        "GR",
        35.3397,
        25.1803,
    ),
    ("RHO", "LGRP", "Rhodes Diagoras", "Rhodes", "Greece", "GR", 36.4054, 28.0862),
    (
        "CFU",
        "LGKR",
        "Corfu Ioannis Kapodistrias",
        "Corfu",
        "Greece",
        "GR",
        39.6019,
        19.9117,
    ),
    ("MYK", "LGMK", "Mykonos", "Mykonos", "Greece", "GR", 37.4351, 25.3481),
    ("JTR", "LGSR", "Santorini (Thira)", "Santorini", "Greece", "GR", 36.3992, 25.4793),
    (
        "LCA",
        "LCLK",
        "Larnaca International",
        "Larnaca",
        "Cyprus",
        "CY",
        34.8751,
        33.6249,
    ),
    ("PFO", "LCPH", "Paphos International", "Paphos", "Cyprus", "CY", 34.7180, 32.4857),
    # ── Turkey ─────────────────────────────────────────────────────────────
    ("IST", "LTFM", "Istanbul", "Istanbul", "Turkey", "TR", 41.2753, 28.7519),
    (
        "SAW",
        "LTFJ",
        "Istanbul Sabiha Gökçen",
        "Istanbul",
        "Turkey",
        "TR",
        40.8983,
        29.3092,
    ),
    ("AYT", "LTAI", "Antalya", "Antalya", "Turkey", "TR", 36.8987, 30.8006),
    ("ESB", "LTAC", "Ankara Esenboğa", "Ankara", "Turkey", "TR", 40.1281, 32.9951),
    ("ADB", "LTBJ", "Izmir Adnan Menderes", "Izmir", "Turkey", "TR", 38.2924, 27.1570),
    ("DLM", "LTBS", "Dalaman", "Dalaman", "Turkey", "TR", 36.7131, 28.7925),
    ("BJV", "LTFE", "Bodrum Milas", "Bodrum", "Turkey", "TR", 37.2506, 27.6643),
    ("TZX", "LTCG", "Trabzon", "Trabzon", "Turkey", "TR", 40.9950, 39.7897),
    # ── Middle East ────────────────────────────────────────────────────────
    (
        "DXB",
        "OMDB",
        "Dubai International",
        "Dubai",
        "United Arab Emirates",
        "AE",
        25.2528,
        55.3644,
    ),
    (
        "AUH",
        "OMAA",
        "Abu Dhabi International",
        "Abu Dhabi",
        "United Arab Emirates",
        "AE",
        24.4330,
        54.6511,
    ),
    (
        "SHJ",
        "OMSJ",
        "Sharjah International",
        "Sharjah",
        "United Arab Emirates",
        "AE",
        25.3286,
        55.5172,
    ),
    (
        "DWC",
        "OMDW",
        "Al Maktoum International",
        "Dubai",
        "United Arab Emirates",
        "AE",
        24.8963,
        55.1613,
    ),
    ("DOH", "OTHH", "Hamad International", "Doha", "Qatar", "QA", 25.2731, 51.6081),
    (
        "BAH",
        "OBBI",
        "Bahrain International",
        "Manama",
        "Bahrain",
        "BH",
        26.2708,
        50.6336,
    ),
    (
        "KWI",
        "OKBK",
        "Kuwait International",
        "Kuwait City",
        "Kuwait",
        "KW",
        29.2267,
        47.9689,
    ),
    ("MCT", "OOMS", "Muscat International", "Muscat", "Oman", "OM", 23.5933, 58.2844),
    ("SLL", "OOSA", "Salalah", "Salalah", "Oman", "OM", 17.0387, 54.0913),
    (
        "AMM",
        "OJAM",
        "Queen Alia International",
        "Amman",
        "Jordan",
        "JO",
        31.7226,
        35.9932,
    ),
    (
        "BEY",
        "OLBA",
        "Rafic Hariri International",
        "Beirut",
        "Lebanon",
        "LB",
        33.8209,
        35.4884,
    ),
    (
        "TLV",
        "LLBG",
        "Ben Gurion International",
        "Tel Aviv",
        "Israel",
        "IL",
        32.0055,
        34.8854,
    ),
    ("ETH", "LLET", "Eilat J. Hozman", "Eilat", "Israel", "IL", 29.5613, 34.9600),
    ("BGW", "ORBI", "Baghdad International", "Baghdad", "Iraq", "IQ", 33.2626, 44.2346),
    ("EBL", "ORER", "Erbil International", "Erbil", "Iraq", "IQ", 36.2376, 43.9632),
    (
        "IKA",
        "OIIE",
        "Tehran Imam Khomeini International",
        "Tehran",
        "Iran",
        "IR",
        35.4161,
        51.1522,
    ),
    (
        "MHD",
        "OIMM",
        "Mashhad Shahid Hashemi Nejad",
        "Mashhad",
        "Iran",
        "IR",
        36.2352,
        59.6410,
    ),
    (
        "RUH",
        "OERK",
        "King Khalid International",
        "Riyadh",
        "Saudi Arabia",
        "SA",
        24.9578,
        46.6989,
    ),
    (
        "JED",
        "OEJN",
        "King Abdulaziz International",
        "Jeddah",
        "Saudi Arabia",
        "SA",
        21.6796,
        39.1565,
    ),
    (
        "DMM",
        "OEDF",
        "King Fahd International",
        "Dammam",
        "Saudi Arabia",
        "SA",
        26.4712,
        49.7979,
    ),
    (
        "MED",
        "OEMA",
        "Prince Mohammad bin Abdulaziz International",
        "Medina",
        "Saudi Arabia",
        "SA",
        24.5534,
        39.7051,
    ),
    ("AHB", "OEAB", "Abha Regional", "Abha", "Saudi Arabia", "SA", 18.2404, 42.6566),
    ("YNB", "OEYN", "Yanbu Airport", "Yanbu", "Saudi Arabia", "SA", 24.1442, 38.0634),
    # ── India ──────────────────────────────────────────────────────────────
    (
        "DEL",
        "VIDP",
        "Indira Gandhi International",
        "Delhi",
        "India",
        "IN",
        28.5562,
        77.1000,
    ),
    (
        "BOM",
        "VABB",
        "Chhatrapati Shivaji Maharaj International",
        "Mumbai",
        "India",
        "IN",
        19.0896,
        72.8656,
    ),
    (
        "BLR",
        "VOBL",
        "Kempegowda International",
        "Bangalore",
        "India",
        "IN",
        13.1979,
        77.7063,
    ),
    (
        "MAA",
        "VOMM",
        "Chennai International",
        "Chennai",
        "India",
        "IN",
        12.9900,
        80.1693,
    ),
    (
        "CCU",
        "VECC",
        "Netaji Subhash Chandra Bose International",
        "Kolkata",
        "India",
        "IN",
        22.6520,
        88.4463,
    ),
    (
        "HYD",
        "VOHS",
        "Rajiv Gandhi International",
        "Hyderabad",
        "India",
        "IN",
        17.2313,
        78.4298,
    ),
    ("COK", "VOCI", "Cochin International", "Kochi", "India", "IN", 10.1520, 76.3919),
    ("PNQ", "VAPO", "Pune Airport", "Pune", "India", "IN", 18.5822, 73.9197),
    (
        "AMD",
        "VAAH",
        "Sardar Vallabhbhai Patel International",
        "Ahmedabad",
        "India",
        "IN",
        23.0771,
        72.6347,
    ),
    (
        "GOI",
        "VAGO",
        "Goa International (Dabolim)",
        "Goa",
        "India",
        "IN",
        15.3808,
        73.8314,
    ),
    ("JAI", "VIJP", "Jaipur International", "Jaipur", "India", "IN", 26.8242, 75.8122),
    (
        "LKO",
        "VILK",
        "Chaudhary Charan Singh International",
        "Lucknow",
        "India",
        "IN",
        26.7606,
        80.8893,
    ),
    (
        "TRV",
        "VOTV",
        "Trivandrum International",
        "Thiruvananthapuram",
        "India",
        "IN",
        8.4812,
        76.9201,
    ),
    (
        "IXC",
        "VICG",
        "Chandigarh International",
        "Chandigarh",
        "India",
        "IN",
        30.6735,
        76.7885,
    ),
    (
        "ATQ",
        "VIAR",
        "Sri Guru Ram Dass Jee International",
        "Amritsar",
        "India",
        "IN",
        31.7096,
        74.7973,
    ),
    (
        "GAU",
        "VEGT",
        "Lokpriya Gopinath Bordoloi International",
        "Guwahati",
        "India",
        "IN",
        26.1061,
        91.5859,
    ),
    (
        "BBI",
        "VEBS",
        "Biju Patnaik International",
        "Bhubaneswar",
        "India",
        "IN",
        20.2444,
        85.8178,
    ),
    ("IXB", "VEBD", "Bagdogra Airport", "Siliguri", "India", "IN", 26.6812, 88.3286),
    (
        "CCJ",
        "VOCL",
        "Calicut International",
        "Kozhikode",
        "India",
        "IN",
        11.1368,
        75.9528,
    ),
    (
        "NAG",
        "VANP",
        "Dr. Babasaheb Ambedkar International",
        "Nagpur",
        "India",
        "IN",
        21.0922,
        79.0472,
    ),
    (
        "VGA",
        "VOVZ",
        "Vijayawada Airport",
        "Vijayawada",
        "India",
        "IN",
        16.5304,
        80.7965,
    ),
    (
        "TRZ",
        "VOTY",
        "Tiruchirappalli International",
        "Trichy",
        "India",
        "IN",
        10.7654,
        78.7097,
    ),
    ("IXM", "VOMD", "Madurai Airport", "Madurai", "India", "IN", 9.8345, 78.0934),
    ("RAJ", "VARK", "Rajkot Airport", "Rajkot", "India", "IN", 22.3092, 70.7796),
    ("BDQ", "VABO", "Vadodara Airport", "Vadodara", "India", "IN", 22.3362, 73.2263),
    (
        "VNS",
        "VIBN",
        "Lal Bahadur Shastri International",
        "Varanasi",
        "India",
        "IN",
        25.4524,
        82.8593,
    ),
    (
        "PAT",
        "VEPT",
        "Jay Prakash Narayan International",
        "Patna",
        "India",
        "IN",
        25.5913,
        85.0880,
    ),
    (
        "IDR",
        "VAID",
        "Devi Ahilyabai Holkar Airport",
        "Indore",
        "India",
        "IN",
        22.7218,
        75.8011,
    ),
    ("BHO", "VABP", "Raja Bhoj Airport", "Bhopal", "India", "IN", 23.2875, 77.3374),
    (
        "SXR",
        "VISR",
        "Sheikh ul Alam International",
        "Srinagar",
        "India",
        "IN",
        33.9871,
        74.7742,
    ),
    ("IXL", "VILH", "Kushok Bakula Rimpochhe", "Leh", "India", "IN", 34.1359, 77.5465),
    # ── Pakistan & Sri Lanka & Bangladesh ──────────────────────────────────
    (
        "KHI",
        "OPKC",
        "Jinnah International",
        "Karachi",
        "Pakistan",
        "PK",
        24.9065,
        67.1608,
    ),
    (
        "LHE",
        "OPLA",
        "Allama Iqbal International",
        "Lahore",
        "Pakistan",
        "PK",
        31.5216,
        74.4036,
    ),
    (
        "ISB",
        "OPIS",
        "Islamabad International",
        "Islamabad",
        "Pakistan",
        "PK",
        33.5491,
        72.8316,
    ),
    (
        "PEW",
        "OPPS",
        "Bacha Khan International",
        "Peshawar",
        "Pakistan",
        "PK",
        33.9939,
        71.5146,
    ),
    (
        "CMB",
        "VCBI",
        "Bandaranaike International",
        "Colombo",
        "Sri Lanka",
        "LK",
        7.1808,
        79.8841,
    ),
    (
        "DAC",
        "VGHS",
        "Hazrat Shahjalal International",
        "Dhaka",
        "Bangladesh",
        "BD",
        23.8433,
        90.3978,
    ),
    (
        "CGP",
        "VGEG",
        "Shah Amanat International",
        "Chittagong",
        "Bangladesh",
        "BD",
        22.2496,
        91.8133,
    ),
    (
        "KTM",
        "VNKT",
        "Tribhuvan International",
        "Kathmandu",
        "Nepal",
        "NP",
        27.6966,
        85.3591,
    ),
    (
        "RGN",
        "VYYY",
        "Yangon International",
        "Yangon",
        "Myanmar",
        "MM",
        16.9073,
        96.1332,
    ),
    (
        "MDL",
        "VYMD",
        "Mandalay International",
        "Mandalay",
        "Myanmar",
        "MM",
        21.7022,
        95.9779,
    ),
    # ── Southeast Asia ─────────────────────────────────────────────────────
    ("BKK", "VTBS", "Suvarnabhumi", "Bangkok", "Thailand", "TH", 13.6900, 100.7501),
    (
        "DMK",
        "VTBD",
        "Don Mueang International",
        "Bangkok",
        "Thailand",
        "TH",
        13.9126,
        100.6068,
    ),
    (
        "HKT",
        "VTSP",
        "Phuket International",
        "Phuket",
        "Thailand",
        "TH",
        8.1132,
        98.3169,
    ),
    (
        "CNX",
        "VTCC",
        "Chiang Mai International",
        "Chiang Mai",
        "Thailand",
        "TH",
        18.7668,
        98.9628,
    ),
    (
        "USM",
        "VTSM",
        "Koh Samui Airport",
        "Koh Samui",
        "Thailand",
        "TH",
        9.5478,
        100.0630,
    ),
    (
        "SIN",
        "WSSS",
        "Singapore Changi",
        "Singapore",
        "Singapore",
        "SG",
        1.3644,
        103.9915,
    ),
    (
        "KUL",
        "WMKK",
        "Kuala Lumpur International",
        "Kuala Lumpur",
        "Malaysia",
        "MY",
        2.7456,
        101.7099,
    ),
    (
        "PEN",
        "WMKP",
        "Penang International",
        "Penang",
        "Malaysia",
        "MY",
        5.2971,
        100.2769,
    ),
    (
        "BKI",
        "WBKK",
        "Kota Kinabalu International",
        "Kota Kinabalu",
        "Malaysia",
        "MY",
        5.9372,
        116.0514,
    ),
    (
        "CGK",
        "WIII",
        "Soekarno-Hatta International",
        "Jakarta",
        "Indonesia",
        "ID",
        -6.1256,
        106.6559,
    ),
    (
        "DPS",
        "WADD",
        "Ngurah Rai International (Bali)",
        "Bali",
        "Indonesia",
        "ID",
        -8.7482,
        115.1670,
    ),
    (
        "SUB",
        "WARR",
        "Juanda International",
        "Surabaya",
        "Indonesia",
        "ID",
        -7.3798,
        112.7869,
    ),
    (
        "UPG",
        "WAAA",
        "Sultan Hasanuddin International",
        "Makassar",
        "Indonesia",
        "ID",
        -5.0616,
        119.5540,
    ),
    (
        "MNL",
        "RPLL",
        "Ninoy Aquino International",
        "Manila",
        "Philippines",
        "PH",
        14.5086,
        121.0197,
    ),
    (
        "CEB",
        "RPVM",
        "Mactan-Cebu International",
        "Cebu",
        "Philippines",
        "PH",
        10.3075,
        123.9790,
    ),
    (
        "DVO",
        "RPMD",
        "Francisco Bangoy International",
        "Davao",
        "Philippines",
        "PH",
        7.1255,
        125.6458,
    ),
    (
        "SGN",
        "VVTS",
        "Tan Son Nhat International",
        "Ho Chi Minh City",
        "Vietnam",
        "VN",
        10.8188,
        106.6520,
    ),
    (
        "HAN",
        "VVNB",
        "Noi Bai International",
        "Hanoi",
        "Vietnam",
        "VN",
        21.2212,
        105.8072,
    ),
    (
        "DAD",
        "VVDN",
        "Da Nang International",
        "Da Nang",
        "Vietnam",
        "VN",
        16.0439,
        108.1993,
    ),
    (
        "PNH",
        "VDPP",
        "Phnom Penh International",
        "Phnom Penh",
        "Cambodia",
        "KH",
        11.5466,
        104.8440,
    ),
    (
        "REP",
        "VDSR",
        "Siem Reap–Angkor International",
        "Siem Reap",
        "Cambodia",
        "KH",
        13.4107,
        103.8130,
    ),
    (
        "VTE",
        "VLVT",
        "Wattay International",
        "Vientiane",
        "Laos",
        "LA",
        17.9883,
        102.5633,
    ),
    # ── East Asia ──────────────────────────────────────────────────────────
    (
        "HKG",
        "VHHH",
        "Hong Kong International",
        "Hong Kong",
        "Hong Kong",
        "HK",
        22.3080,
        113.9185,
    ),
    ("MFM", "VMMC", "Macau International", "Macau", "Macau", "MO", 22.1496, 113.5916),
    (
        "PEK",
        "ZBAA",
        "Beijing Capital International",
        "Beijing",
        "China",
        "CN",
        40.0799,
        116.6031,
    ),
    (
        "PKX",
        "ZBAD",
        "Beijing Daxing International",
        "Beijing",
        "China",
        "CN",
        39.5098,
        116.4105,
    ),
    (
        "PVG",
        "ZSPD",
        "Shanghai Pudong International",
        "Shanghai",
        "China",
        "CN",
        31.1443,
        121.8083,
    ),
    (
        "SHA",
        "ZSSS",
        "Shanghai Hongqiao International",
        "Shanghai",
        "China",
        "CN",
        31.1979,
        121.3362,
    ),
    (
        "CAN",
        "ZGGG",
        "Guangzhou Baiyun International",
        "Guangzhou",
        "China",
        "CN",
        23.3924,
        113.2990,
    ),
    (
        "SZX",
        "ZGSZ",
        "Shenzhen Bao'an International",
        "Shenzhen",
        "China",
        "CN",
        22.6393,
        113.8107,
    ),
    (
        "CTU",
        "ZUUU",
        "Chengdu Tianfu International",
        "Chengdu",
        "China",
        "CN",
        30.5898,
        104.2740,
    ),
    (
        "TFU",
        "ZUTF",
        "Chengdu Shuangliu International",
        "Chengdu",
        "China",
        "CN",
        30.5781,
        103.9472,
    ),
    (
        "KMG",
        "ZPPP",
        "Kunming Changshui International",
        "Kunming",
        "China",
        "CN",
        24.9920,
        102.7443,
    ),
    (
        "XIY",
        "ZLXY",
        "Xi'an Xianyang International",
        "Xian",
        "China",
        "CN",
        34.4471,
        108.7516,
    ),
    (
        "WUH",
        "ZHHH",
        "Wuhan Tianhe International",
        "Wuhan",
        "China",
        "CN",
        30.7838,
        114.2081,
    ),
    (
        "HGH",
        "ZSHC",
        "Hangzhou Xiaoshan International",
        "Hangzhou",
        "China",
        "CN",
        30.2295,
        120.4295,
    ),
    (
        "NKG",
        "ZSNJ",
        "Nanjing Lukou International",
        "Nanjing",
        "China",
        "CN",
        31.7420,
        118.8620,
    ),
    (
        "TNA",
        "ZSJN",
        "Jinan Yaoqiang International",
        "Jinan",
        "China",
        "CN",
        36.8572,
        117.2160,
    ),
    (
        "CGO",
        "ZHCC",
        "Zhengzhou Xinzheng International",
        "Zhengzhou",
        "China",
        "CN",
        34.5197,
        113.8408,
    ),
    (
        "TAO",
        "ZSQD",
        "Qingdao Jiaodong International",
        "Qingdao",
        "China",
        "CN",
        36.3663,
        120.0821,
    ),
    (
        "SHE",
        "ZYYY",
        "Shenyang Taoxian International",
        "Shenyang",
        "China",
        "CN",
        41.6398,
        123.4834,
    ),
    (
        "HAK",
        "ZJHK",
        "Haikou Meilan International",
        "Haikou",
        "China",
        "CN",
        19.9349,
        110.4589,
    ),
    (
        "SYX",
        "ZJSY",
        "Sanya Phoenix International",
        "Sanya",
        "China",
        "CN",
        18.3029,
        109.4122,
    ),
    (
        "CSX",
        "ZGHA",
        "Changsha Huanghua International",
        "Changsha",
        "China",
        "CN",
        28.1892,
        113.2203,
    ),
    (
        "CKG",
        "ZUCK",
        "Chongqing Jiangbei International",
        "Chongqing",
        "China",
        "CN",
        29.7192,
        106.6417,
    ),
    (
        "HET",
        "ZBHH",
        "Hohhot Baita International",
        "Hohhot",
        "China",
        "CN",
        40.8514,
        111.8240,
    ),
    (
        "URC",
        "ZWWW",
        "Ürümqi Diwopu International",
        "Urumqi",
        "China",
        "CN",
        43.9071,
        87.4742,
    ),
    (
        "LHW",
        "ZLLL",
        "Lanzhou Zhongchuan International",
        "Lanzhou",
        "China",
        "CN",
        36.5152,
        103.6208,
    ),
    (
        "INC",
        "ZLIC",
        "Yinchuan Hedong International",
        "Yinchuan",
        "China",
        "CN",
        38.4822,
        106.0093,
    ),
    (
        "XMN",
        "ZSAM",
        "Xiamen Gaoqi International",
        "Xiamen",
        "China",
        "CN",
        24.5440,
        118.1275,
    ),
    (
        "FOC",
        "ZSFZ",
        "Fuzhou Changle International",
        "Fuzhou",
        "China",
        "CN",
        25.9351,
        119.6631,
    ),
    (
        "NNG",
        "ZGNN",
        "Nanning Wuxu International",
        "Nanning",
        "China",
        "CN",
        22.6083,
        108.1723,
    ),
    (
        "KWE",
        "ZUGY",
        "Guiyang Longdongbao International",
        "Guiyang",
        "China",
        "CN",
        26.5385,
        106.8012,
    ),
    (
        "HRB",
        "ZYHB",
        "Harbin Taiping International",
        "Harbin",
        "China",
        "CN",
        45.6234,
        126.2500,
    ),
    (
        "DLC",
        "ZYTL",
        "Dalian Zhoushuizi International",
        "Dalian",
        "China",
        "CN",
        38.9657,
        121.5386,
    ),
    (
        "ICN",
        "RKSI",
        "Incheon International",
        "Seoul",
        "South Korea",
        "KR",
        37.4691,
        126.4505,
    ),
    (
        "GMP",
        "RKSS",
        "Gimpo International",
        "Seoul",
        "South Korea",
        "KR",
        37.5583,
        126.7906,
    ),
    (
        "PUS",
        "RKPK",
        "Gimhae International",
        "Busan",
        "South Korea",
        "KR",
        35.1795,
        128.9382,
    ),
    (
        "CJU",
        "RKPC",
        "Jeju International",
        "Jeju",
        "South Korea",
        "KR",
        33.5113,
        126.4930,
    ),
    (
        "TAE",
        "RKTN",
        "Daegu International",
        "Daegu",
        "South Korea",
        "KR",
        35.8941,
        128.6589,
    ),
    (
        "NRT",
        "RJAA",
        "Tokyo Narita International",
        "Tokyo",
        "Japan",
        "JP",
        35.7720,
        140.3929,
    ),
    ("HND", "RJTT", "Tokyo Haneda", "Tokyo", "Japan", "JP", 35.5494, 139.7798),
    ("KIX", "RJBB", "Kansai International", "Osaka", "Japan", "JP", 34.4274, 135.2440),
    ("ITM", "RJOO", "Osaka Itami", "Osaka", "Japan", "JP", 34.7855, 135.4386),
    (
        "NGO",
        "RJGG",
        "Chubu Centrair International",
        "Nagoya",
        "Japan",
        "JP",
        34.8583,
        136.8054,
    ),
    (
        "CTS",
        "RJCC",
        "New Chitose International",
        "Sapporo",
        "Japan",
        "JP",
        42.7752,
        141.6922,
    ),
    ("FUK", "RJFF", "Fukuoka", "Fukuoka", "Japan", "JP", 33.5859, 130.4511),
    ("OKA", "ROAH", "Naha", "Okinawa", "Japan", "JP", 26.1958, 127.6461),
    ("HIJ", "RJOA", "Hiroshima", "Hiroshima", "Japan", "JP", 34.4361, 132.9194),
    ("SDJ", "RJSS", "Sendai", "Sendai", "Japan", "JP", 38.1397, 140.9170),
    ("KMJ", "RJFT", "Kumamoto", "Kumamoto", "Japan", "JP", 32.8373, 130.8551),
    (
        "TPE",
        "RCTP",
        "Taiwan Taoyuan International",
        "Taipei",
        "Taiwan",
        "TW",
        25.0777,
        121.2325,
    ),
    ("TSA", "RCSS", "Taipei Songshan", "Taipei", "Taiwan", "TW", 25.0694, 121.5526),
    (
        "KHH",
        "RCKH",
        "Kaohsiung International",
        "Kaohsiung",
        "Taiwan",
        "TW",
        22.5771,
        120.3501,
    ),
    (
        "ULN",
        "ZMUB",
        "Chinggis Khaan International",
        "Ulaanbaatar",
        "Mongolia",
        "MN",
        47.8431,
        106.7660,
    ),
    # ── Australia & Oceania ────────────────────────────────────────────────
    (
        "SYD",
        "YSSY",
        "Sydney Kingsford Smith",
        "Sydney",
        "Australia",
        "AU",
        -33.9399,
        151.1753,
    ),
    ("MEL", "YMML", "Melbourne", "Melbourne", "Australia", "AU", -37.6690, 144.8410),
    ("BNE", "YBBN", "Brisbane", "Brisbane", "Australia", "AU", -27.3842, 153.1175),
    ("PER", "YPPH", "Perth", "Perth", "Australia", "AU", -31.9403, 115.9670),
    ("ADL", "YPAD", "Adelaide", "Adelaide", "Australia", "AU", -34.9452, 138.5306),
    ("CBR", "YSCB", "Canberra", "Canberra", "Australia", "AU", -35.3069, 149.1950),
    ("CNS", "YBCS", "Cairns", "Cairns", "Australia", "AU", -16.8858, 145.7552),
    ("DRW", "YPDN", "Darwin", "Darwin", "Australia", "AU", -12.4147, 130.8765),
    ("HBA", "YMHB", "Hobart", "Hobart", "Australia", "AU", -42.8361, 147.5103),
    ("OOL", "YBCG", "Gold Coast", "Gold Coast", "Australia", "AU", -28.1644, 153.5047),
    ("TSV", "YBTL", "Townsville", "Townsville", "Australia", "AU", -19.2525, 146.7651),
    ("AKL", "NZAA", "Auckland", "Auckland", "New Zealand", "NZ", -37.0082, 174.7850),
    (
        "CHC",
        "NZCH",
        "Christchurch",
        "Christchurch",
        "New Zealand",
        "NZ",
        -43.4894,
        172.5320,
    ),
    (
        "WLG",
        "NZWN",
        "Wellington",
        "Wellington",
        "New Zealand",
        "NZ",
        -41.3272,
        174.8050,
    ),
    (
        "ZQN",
        "NZQN",
        "Queenstown",
        "Queenstown",
        "New Zealand",
        "NZ",
        -45.0211,
        168.7392,
    ),
    ("NAN", "NFFN", "Nadi International", "Nadi", "Fiji", "FJ", -17.7554, 177.4431),
    (
        "PPT",
        "NTAA",
        "Faa'a International (Tahiti)",
        "Papeete",
        "French Polynesia",
        "PF",
        -17.5534,
        -149.6063,
    ),
    (
        "APW",
        "NSFA",
        "Fagali'i Airport (Apia)",
        "Apia",
        "Samoa",
        "WS",
        -13.8299,
        -171.9950,
    ),
    (
        "TBU",
        "NFTF",
        "Fua'amotu International",
        "Nukualofa",
        "Tonga",
        "TO",
        -21.2412,
        -175.1496,
    ),
    (
        "NOU",
        "NWWW",
        "La Tontouta International",
        "Noumea",
        "New Caledonia",
        "NC",
        -22.0146,
        166.2130,
    ),
    # ── Africa ─────────────────────────────────────────────────────────────
    ("CAI", "HECA", "Cairo International", "Cairo", "Egypt", "EG", 30.1219, 31.4056),
    (
        "HRG",
        "HEGN",
        "Hurghada International",
        "Hurghada",
        "Egypt",
        "EG",
        27.1783,
        33.7994,
    ),
    (
        "SSH",
        "HESH",
        "Sharm el-Sheikh International",
        "Sharm el-Sheikh",
        "Egypt",
        "EG",
        27.9773,
        34.3950,
    ),
    ("LXR", "HELX", "Luxor International", "Luxor", "Egypt", "EG", 25.6710, 32.7066),
    (
        "CMN",
        "GMMN",
        "Mohammed V International",
        "Casablanca",
        "Morocco",
        "MA",
        33.3675,
        -7.5899,
    ),
    ("RAK", "GMMX", "Marrakesh Menara", "Marrakech", "Morocco", "MA", 31.6069, -8.0363),
    ("AGA", "GMAD", "Al Massira", "Agadir", "Morocco", "MA", 30.3250, -9.4131),
    ("FEZ", "GMFF", "Fès-Saïss", "Fes", "Morocco", "MA", 33.9273, -4.9778),
    (
        "TNG",
        "GMTT",
        "Ibn Batouta International",
        "Tangier",
        "Morocco",
        "MA",
        35.7269,
        -5.9159,
    ),
    ("ALG", "DAAG", "Houari Boumediene", "Algiers", "Algeria", "DZ", 36.6910, 3.2154),
    ("TUN", "DTTA", "Tunis-Carthage", "Tunis", "Tunisia", "TN", 36.8510, 10.2272),
    (
        "TIP",
        "HLLT",
        "Tripoli International",
        "Tripoli",
        "Libya",
        "LY",
        32.6635,
        13.1590,
    ),
    (
        "ADD",
        "HAAB",
        "Addis Ababa Bole International",
        "Addis Ababa",
        "Ethiopia",
        "ET",
        8.9779,
        38.7993,
    ),
    (
        "NBO",
        "HKNA",
        "Jomo Kenyatta International",
        "Nairobi",
        "Kenya",
        "KE",
        -1.3192,
        36.9275,
    ),
    (
        "MBA",
        "HKMO",
        "Mombasa Moi International",
        "Mombasa",
        "Kenya",
        "KE",
        -4.0348,
        39.5942,
    ),
    (
        "DAR",
        "HTDA",
        "Julius Nyerere International",
        "Dar es Salaam",
        "Tanzania",
        "TZ",
        -6.8781,
        39.2026,
    ),
    (
        "ZNZ",
        "HTZA",
        "Abeid Amani Karume International (Zanzibar)",
        "Zanzibar",
        "Tanzania",
        "TZ",
        -6.2220,
        39.2249,
    ),
    (
        "JNB",
        "FAOR",
        "O.R. Tambo International",
        "Johannesburg",
        "South Africa",
        "ZA",
        -26.1392,
        28.2460,
    ),
    (
        "CPT",
        "FACT",
        "Cape Town International",
        "Cape Town",
        "South Africa",
        "ZA",
        -33.9648,
        18.6017,
    ),
    (
        "DUR",
        "FADU",
        "King Shaka International",
        "Durban",
        "South Africa",
        "ZA",
        -29.6144,
        31.1197,
    ),
    (
        "LOS",
        "DNMM",
        "Murtala Muhammed International",
        "Lagos",
        "Nigeria",
        "NG",
        6.5774,
        3.3212,
    ),
    (
        "ABV",
        "DNAA",
        "Nnamdi Azikiwe International",
        "Abuja",
        "Nigeria",
        "NG",
        9.0069,
        7.2632,
    ),
    ("ACC", "DGAA", "Kotoka International", "Accra", "Ghana", "GH", 5.6052, -0.1669),
    (
        "ABJ",
        "DIAP",
        "Félix Houphouët-Boigny International",
        "Abidjan",
        "Cote d'Ivoire",
        "CI",
        5.2614,
        -3.9263,
    ),
    (
        "DKR",
        "GOOY",
        "Blaise Diagne International",
        "Dakar",
        "Senegal",
        "SN",
        14.6704,
        -17.0728,
    ),
    (
        "CMR",
        "FKYS",
        "Yaoundé Nsimalen International",
        "Yaounde",
        "Cameroon",
        "CM",
        3.7223,
        11.5532,
    ),
    ("DLA", "FKKD", "Douala International", "Douala", "Cameroon", "CM", 4.0061, 9.7195),
    (
        "MRU",
        "FIMP",
        "Sir Seewoosagur Ramgoolam International",
        "Mauritius",
        "Mauritius",
        "MU",
        -20.4302,
        57.6836,
    ),
    (
        "SEZ",
        "FSIA",
        "Seychelles International",
        "Victoria",
        "Seychelles",
        "SC",
        -4.6743,
        55.5218,
    ),
    (
        "ANT",
        "FMEE",
        "Roland Garros (Reunion)",
        "Saint-Denis",
        "Reunion",
        "RE",
        -20.8871,
        55.5103,
    ),
    (
        "TNR",
        "FMMI",
        "Ivato International (Antananarivo)",
        "Antananarivo",
        "Madagascar",
        "MG",
        -18.7969,
        47.4788,
    ),
    (
        "MPM",
        "FQMA",
        "Maputo International",
        "Maputo",
        "Mozambique",
        "MZ",
        -25.9208,
        32.5726,
    ),
    (
        "LUN",
        "FLLS",
        "Kenneth Kaunda International",
        "Lusaka",
        "Zambia",
        "ZM",
        -15.3308,
        28.4526,
    ),
    (
        "HRE",
        "FVHA",
        "Robert Gabriel Mugabe International",
        "Harare",
        "Zimbabwe",
        "ZW",
        -17.9318,
        31.0929,
    ),
    (
        "BLZ",
        "FWCL",
        "Chileka International",
        "Blantyre",
        "Malawi",
        "MW",
        -15.6791,
        34.9740,
    ),
    (
        "EBB",
        "HUEN",
        "Entebbe International",
        "Kampala",
        "Uganda",
        "UG",
        0.0424,
        32.4435,
    ),
    ("KGL", "HRYR", "Kigali International", "Kigali", "Rwanda", "RW", -1.9686, 30.1395),
    (
        "BKO",
        "GABS",
        "Modibo Keita International",
        "Bamako",
        "Mali",
        "ML",
        12.5335,
        -7.9499,
    ),
    (
        "OUA",
        "DFFD",
        "Thomas Sankara International",
        "Ouagadougou",
        "Burkina Faso",
        "BF",
        12.3532,
        -1.5124,
    ),
    (
        "NIY",
        "GFLL",
        "Lungi International",
        "Freetown",
        "Sierra Leone",
        "SL",
        8.6165,
        -13.1955,
    ),
    ("COO", "DBBB", "Cadjehoun Airport", "Cotonou", "Benin", "BJ", 6.3572, 2.3845),
    ("LFW", "DXXX", "Lomé-Tokoin International", "Lome", "Togo", "TG", 6.1657, 1.2545),
    (
        "OXB",
        "GOGB",
        "Osvaldo Vieira International",
        "Bissau",
        "Guinea-Bissau",
        "GW",
        11.8948,
        -15.6537,
    ),
    (
        "CKY",
        "GUCY",
        "Conakry International",
        "Conakry",
        "Guinea",
        "GN",
        9.5769,
        -13.6120,
    ),
    (
        "SSG",
        "FGSL",
        "Malabo International",
        "Malabo",
        "Equatorial Guinea",
        "GQ",
        3.7553,
        8.7087,
    ),
    (
        "LBV",
        "FOOL",
        "Leon M'ba International",
        "Libreville",
        "Gabon",
        "GA",
        0.4586,
        9.4123,
    ),
    (
        "BZV",
        "FCBB",
        "Maya-Maya Airport",
        "Brazzaville",
        "Republic of the Congo",
        "CG",
        -4.2517,
        15.2531,
    ),
    (
        "FIH",
        "FZAA",
        "Ndjili International",
        "Kinshasa",
        "Democratic Republic of the Congo",
        "CD",
        -4.3858,
        15.4446,
    ),
    (
        "LAD",
        "FNLU",
        "Quatro de Fevereiro International",
        "Luanda",
        "Angola",
        "AO",
        -8.8584,
        13.2312,
    ),
    (
        "WDH",
        "FYWH",
        "Hosea Kutako International",
        "Windhoek",
        "Namibia",
        "NA",
        -22.4799,
        17.4709,
    ),
    (
        "GBE",
        "FBSK",
        "Sir Seretse Khama International",
        "Gaborone",
        "Botswana",
        "BW",
        -24.5552,
        25.9182,
    ),
    (
        "KHO",
        "FXKH",
        "Moshoeshoe I International",
        "Maseru",
        "Lesotho",
        "LS",
        -29.4623,
        27.5525,
    ),
]


def seed():
    """Create tables and insert airport data if not already seeded."""
    from .database import is_seeded

    create_tables()
    if is_seeded():
        print("Database already seeded — skipping.")
        return

    # Deduplicate by IATA code (keep first occurrence)
    seen = set()
    unique = []
    for row in AIRPORTS:
        code = row[0]
        if code not in seen:
            seen.add(code)
            unique.append(row)

    with get_connection() as conn:
        conn.executemany(
            """
            INSERT OR IGNORE INTO airports
                (iata_code, icao_code, name, city, country, country_code, latitude, longitude)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            unique,
        )
    print(f"Seeded {len(unique)} airports.")


if __name__ == "__main__":
    seed()
